"""Test whether GRU-H200 residual features separate non-FOG from FOG.

This analysis reuses the audited LOSO residual caches produced by
``run_daphnet_gru_horizon_ablation.py``.  For each held-out subject it compares
normal-target residuals with FOG-target residuals, then evaluates:

1. fixed scalar residual scores;
2. a class-balanced logistic model over deterministic time-frequency features;
3. the already-saved H200 residual-TCN result as a sequence-model reference.

The feature classifier is exploratory because the current residual caches for
outer-training subjects were generated by an NBM fitted on those same subjects.
Held-out test feature separation is not affected by that limitation.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import math
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    average_precision_score,
    balanced_accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler


SUBJECTS = ("S01", "S02", "S03", "S05", "S06", "S07", "S08", "S09")
CHANNEL_NAMES = (
    "ankle_acc_forward",
    "ankle_acc_vertical",
    "ankle_acc_lateral",
    "thigh_acc_forward",
    "thigh_acc_vertical",
    "thigh_acc_lateral",
    "trunk_acc_forward",
    "trunk_acc_vertical",
    "trunk_acc_lateral",
)
MAGNITUDE_CHANNELS = (
    "ankle_acc_magnitude",
    "thigh_acc_magnitude",
    "trunk_acc_magnitude",
)
SUMMARY_FEATURE_LABELS = {
    "residual_rms": "Residual RMS",
    "residual_absolute_mean": "Mean |residual|",
    "residual_derivative_rms": "Residual derivative RMS",
    "locomotor_log_power": "log(1 + 0.5–3 Hz power)",
    "freeze_log_power": "log(1 + 3–8 Hz power)",
    "freeze_index_log1p": "log(1 + freeze/locomotor)",
    "spectral_entropy": "Spectral entropy",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--suite-dir",
        type=Path,
        default=Path(
            "outputs/daphnet_gru_horizon4_h4_tcnm_loso_seed42"
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("outputs/daphnet_gru_h200_residual_feature_analysis"),
    )
    parser.add_argument("--feature-batch-size", type=int, default=2048)
    parser.add_argument("--bootstrap-samples", type=int, default=100_000)
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def load_feature_extractor(repo_root: Path):
    module_path = repo_root / "daphnet_baselines" / "features.py"
    spec = importlib.util.spec_from_file_location(
        "_daphnet_residual_tf_features",
        module_path,
    )
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load feature extractor from {module_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module.TimeFrequencyFeatureExtractor


def residual_cache_path(suite_dir: Path, subject: str) -> Path:
    return (
        suite_dir
        / f"loso_{subject}"
        / "horizon_h200_2s"
        / "gru"
        / "residual_cache.npz"
    )


def summary_features(
    features: np.ndarray,
    feature_names: tuple[str, ...],
) -> dict[str, np.ndarray]:
    index = {name: position for position, name in enumerate(feature_names)}

    def magnitude_values(feature: str) -> np.ndarray:
        columns = [
            index[f"{channel}__{feature}"] for channel in MAGNITUDE_CHANNELS
        ]
        return np.asarray(features[:, columns], dtype=np.float64)

    locomotor = magnitude_values("locomotor_power")
    freeze = magnitude_values("freeze_power")
    return {
        "residual_rms": magnitude_values("rms").mean(axis=1),
        "residual_absolute_mean": magnitude_values("absolute_mean").mean(axis=1),
        "residual_derivative_rms": magnitude_values("derivative_rms").mean(axis=1),
        "locomotor_log_power": np.log1p(np.maximum(locomotor, 0.0)).mean(axis=1),
        "freeze_log_power": np.log1p(np.maximum(freeze, 0.0)).mean(axis=1),
        "freeze_index_log1p": magnitude_values("freeze_index_log1p").mean(axis=1),
        "spectral_entropy": magnitude_values("spectral_entropy").mean(axis=1),
    }


def threshold_for_balanced_accuracy(
    y_true: np.ndarray,
    score: np.ndarray,
) -> float:
    fpr, tpr, thresholds = roc_curve(y_true, score)
    balanced = 0.5 * (tpr + 1.0 - fpr)
    best = float(np.nanmax(balanced))
    candidates = thresholds[np.isclose(balanced, best, rtol=0.0, atol=1e-12)]
    finite = candidates[np.isfinite(candidates)]
    if len(finite):
        return float(np.max(finite))
    return float(np.median(score))


def binary_metrics(
    y_true: np.ndarray,
    score: np.ndarray,
    threshold: float,
) -> dict[str, float]:
    prediction = (score >= threshold).astype(np.int8)
    tn, fp, fn, tp = confusion_matrix(
        y_true,
        prediction,
        labels=[0, 1],
    ).ravel()
    specificity = tn / (tn + fp) if tn + fp else math.nan
    return {
        "pr_auc": float(average_precision_score(y_true, score)),
        "roc_auc": float(roc_auc_score(y_true, score)),
        "balanced_accuracy": float(
            balanced_accuracy_score(y_true, prediction)
        ),
        "fog_recall": float(recall_score(y_true, prediction, zero_division=0)),
        "specificity": float(specificity),
        "fog_precision": float(
            precision_score(y_true, prediction, zero_division=0)
        ),
        "fog_f1": float(f1_score(y_true, prediction, zero_division=0)),
        "threshold": float(threshold),
    }


def bootstrap_mean_interval(
    values: np.ndarray,
    samples: int,
    seed: int,
) -> tuple[float, float]:
    values = np.asarray(values, dtype=np.float64)
    rng = np.random.default_rng(seed)
    draws = rng.integers(0, len(values), size=(samples, len(values)))
    means = values[draws].mean(axis=1)
    low, high = np.percentile(means, [2.5, 97.5])
    return float(low), float(high)


def save_csv(path: Path, rows: list[dict]) -> None:
    pd.DataFrame(rows).to_csv(path, index=False, encoding="utf-8")


def load_h200_tcn_metrics(suite_dir: Path) -> pd.DataFrame:
    fold_summary = pd.read_csv(suite_dir / "fold_summary.csv")
    selected = fold_summary.loc[fold_summary["horizon_id"] == "H200"].copy()
    if len(selected) != len(SUBJECTS):
        raise ValueError(
            f"Expected {len(SUBJECTS)} H200 TCN rows, got {len(selected)}"
        )
    return selected


def main() -> None:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[1]
    suite_dir = (repo_root / args.suite_dir).resolve()
    output_dir = (repo_root / args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    extractor_class = load_feature_extractor(repo_root)
    extractor = extractor_class(
        sampling_rate_hz=64,
        channel_names=CHANNEL_NAMES,
        include_triad_magnitudes=True,
        batch_size=args.feature_batch_size,
    )
    feature_names = tuple(extractor.feature_names())

    separation_rows: list[dict] = []
    classifier_rows: list[dict] = []
    coefficient_rows: list[dict] = []
    paired_medians: dict[str, dict[str, tuple[float, float]]] = {
        feature: {} for feature in SUMMARY_FEATURE_LABELS
    }

    for subject_index, subject in enumerate(SUBJECTS):
        cache_path = residual_cache_path(suite_dir, subject)
        if not cache_path.exists():
            raise FileNotFoundError(cache_path)
        print(f"[{subject_index + 1}/{len(SUBJECTS)}] {subject}: loading residuals")
        with np.load(cache_path, allow_pickle=False) as cache:
            train_residual = np.asarray(cache["train_residual"], dtype=np.float32)
            train_y = np.asarray(cache["train_y"], dtype=np.int8)
            validation_residual = np.asarray(
                cache["validation_residual"],
                dtype=np.float32,
            )
            validation_y = np.asarray(cache["validation_y"], dtype=np.int8)
            test_residual = np.asarray(cache["test_residual"], dtype=np.float32)
            test_y = np.asarray(cache["test_y"], dtype=np.int8)

        print(f"[{subject_index + 1}/{len(SUBJECTS)}] {subject}: extracting features")
        train_features = extractor.transform(train_residual)
        validation_features = extractor.transform(validation_residual)
        test_features = extractor.transform(test_residual)
        del train_residual, validation_residual, test_residual

        train_summary = summary_features(train_features, feature_names)
        validation_summary = summary_features(validation_features, feature_names)
        test_summary = summary_features(test_features, feature_names)

        for feature_name, score in test_summary.items():
            nonfog = score[test_y == 0]
            fog = score[test_y == 1]
            median_nonfog = float(np.median(nonfog))
            median_fog = float(np.median(fog))
            paired_medians[feature_name][subject] = (
                median_nonfog,
                median_fog,
            )
            separation_rows.append(
                {
                    "test_subject": subject,
                    "feature": feature_name,
                    "feature_label": SUMMARY_FEATURE_LABELS[feature_name],
                    "n_nonfog": int(len(nonfog)),
                    "n_fog": int(len(fog)),
                    "fog_prevalence": float(np.mean(test_y)),
                    "median_nonfog": median_nonfog,
                    "median_fog": median_fog,
                    "median_difference_fog_minus_nonfog": (
                        median_fog - median_nonfog
                    ),
                    "median_ratio_fog_over_nonfog": (
                        median_fog / max(abs(median_nonfog), 1e-12)
                    ),
                    "roc_auc_high_means_fog": float(
                        roc_auc_score(test_y, score)
                    ),
                    "pr_auc_high_means_fog": float(
                        average_precision_score(test_y, score)
                    ),
                }
            )

        rms_validation = validation_summary["residual_rms"]
        rms_test = test_summary["residual_rms"]
        rms_threshold = threshold_for_balanced_accuracy(
            validation_y,
            rms_validation,
        )
        rms_metrics = binary_metrics(test_y, rms_test, rms_threshold)
        classifier_rows.append(
            {
                "test_subject": subject,
                "method": "residual_rms_threshold",
                "n": int(len(test_y)),
                "n_nonfog": int(np.sum(test_y == 0)),
                "n_fog": int(np.sum(test_y == 1)),
                "fog_prevalence": float(np.mean(test_y)),
                **rms_metrics,
            }
        )

        classifier = Pipeline(
            [
                ("scale", StandardScaler()),
                (
                    "logistic",
                    LogisticRegression(
                        C=1.0,
                        class_weight="balanced",
                        solver="lbfgs",
                        max_iter=2_000,
                        random_state=args.seed,
                    ),
                ),
            ]
        )
        classifier.fit(train_features, train_y)
        validation_probability = classifier.predict_proba(validation_features)[:, 1]
        test_probability = classifier.predict_proba(test_features)[:, 1]
        logistic_threshold = threshold_for_balanced_accuracy(
            validation_y,
            validation_probability,
        )
        logistic_metrics = binary_metrics(
            test_y,
            test_probability,
            logistic_threshold,
        )
        classifier_rows.append(
            {
                "test_subject": subject,
                "method": "time_frequency_logistic",
                "n": int(len(test_y)),
                "n_nonfog": int(np.sum(test_y == 0)),
                "n_fog": int(np.sum(test_y == 1)),
                "fog_prevalence": float(np.mean(test_y)),
                **logistic_metrics,
            }
        )

        logistic = classifier.named_steps["logistic"]
        for feature_name, coefficient in zip(
            feature_names,
            logistic.coef_[0],
        ):
            coefficient_rows.append(
                {
                    "test_subject": subject,
                    "feature": feature_name,
                    "coefficient": float(coefficient),
                    "absolute_coefficient": float(abs(coefficient)),
                }
            )

        del (
            train_features,
            validation_features,
            test_features,
            train_summary,
            validation_summary,
            test_summary,
        )

    save_csv(output_dir / "feature_separation_by_subject.csv", separation_rows)
    save_csv(output_dir / "classifier_fold_metrics.csv", classifier_rows)
    save_csv(output_dir / "logistic_coefficients_by_fold.csv", coefficient_rows)

    separation = pd.DataFrame(separation_rows)
    classifier_frame = pd.DataFrame(classifier_rows)
    coefficients = pd.DataFrame(coefficient_rows)
    tcn = load_h200_tcn_metrics(suite_dir)

    separation_summary_rows: list[dict] = []
    for feature_name in SUMMARY_FEATURE_LABELS:
        selected = separation.loc[separation["feature"] == feature_name]
        auc = selected["roc_auc_high_means_fog"].to_numpy()
        difference = selected[
            "median_difference_fog_minus_nonfog"
        ].to_numpy()
        ci_low, ci_high = bootstrap_mean_interval(
            auc,
            args.bootstrap_samples,
            args.seed,
        )
        separation_summary_rows.append(
            {
                "feature": feature_name,
                "feature_label": SUMMARY_FEATURE_LABELS[feature_name],
                "subject_macro_roc_auc": float(auc.mean()),
                "roc_auc_ci_low": ci_low,
                "roc_auc_ci_high": ci_high,
                "subjects_auc_above_0p5": int(np.sum(auc > 0.5)),
                "subjects_fog_median_higher": int(np.sum(difference > 0.0)),
                "mean_subject_pr_auc": float(
                    selected["pr_auc_high_means_fog"].mean()
                ),
            }
        )
    save_csv(
        output_dir / "feature_separation_summary.csv",
        separation_summary_rows,
    )

    method_summary_rows: list[dict] = []
    for method in ("residual_rms_threshold", "time_frequency_logistic"):
        selected = classifier_frame.loc[classifier_frame["method"] == method]
        for metric in (
            "pr_auc",
            "roc_auc",
            "balanced_accuracy",
            "fog_recall",
            "specificity",
            "fog_f1",
        ):
            values = selected[metric].to_numpy(dtype=np.float64)
            low, high = bootstrap_mean_interval(
                values,
                args.bootstrap_samples,
                args.seed,
            )
            method_summary_rows.append(
                {
                    "method": method,
                    "metric": metric,
                    "subject_macro_mean": float(values.mean()),
                    "subject_std": float(values.std(ddof=0)),
                    "ci_low": low,
                    "ci_high": high,
                }
            )

    tcn_metric_map = {
        "pr_auc": "pr_auc",
        "roc_auc": "roc_auc",
        "balanced_accuracy": "balanced_accuracy",
        "fog_recall": "fog_recall",
        "specificity": "specificity",
        "fog_f1": "fog_f1",
    }
    for metric, column in tcn_metric_map.items():
        values = tcn[column].to_numpy(dtype=np.float64)
        low, high = bootstrap_mean_interval(
            values,
            args.bootstrap_samples,
            args.seed,
        )
        method_summary_rows.append(
            {
                "method": "residual_h4s_tcn_m",
                "metric": metric,
                "subject_macro_mean": float(values.mean()),
                "subject_std": float(values.std(ddof=0)),
                "ci_low": low,
                "ci_high": high,
            }
        )
    save_csv(output_dir / "classifier_summary.csv", method_summary_rows)

    coefficient_summary = (
        coefficients.groupby("feature", as_index=False)
        .agg(
            mean_coefficient=("coefficient", "mean"),
            mean_absolute_coefficient=("absolute_coefficient", "mean"),
            coefficient_positive_folds=("coefficient", lambda x: int((x > 0).sum())),
        )
        .sort_values("mean_absolute_coefficient", ascending=False)
    )
    coefficient_summary.to_csv(
        output_dir / "logistic_feature_importance.csv",
        index=False,
        encoding="utf-8",
    )

    separation_summary = pd.DataFrame(separation_summary_rows)
    method_summary = pd.DataFrame(method_summary_rows)
    plot_results(
        output_dir,
        separation,
        separation_summary,
        classifier_frame,
        method_summary,
        paired_medians,
    )

    baseline_prevalence = float(
        classifier_frame.loc[
            classifier_frame["method"] == "residual_rms_threshold",
            "fog_prevalence",
        ].mean()
    )
    summary_payload = {
        "source_suite": str(suite_dir),
        "source_audit": "pass",
        "horizon_seconds": 2.0,
        "residual_block_shape": "[N,9,128]",
        "subjects": list(SUBJECTS),
        "mean_test_fog_prevalence": baseline_prevalence,
        "feature_separation": separation_summary_rows,
        "classifier_summary": method_summary_rows,
        "interpretation_boundary": (
            "Descriptive test separation is held-out-subject clean. The "
            "exploratory logistic classifier uses current in-fold training "
            "residuals, not subject-cross-fitted NBM residuals."
        ),
    }
    (output_dir / "summary.json").write_text(
        json.dumps(summary_payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    write_report(
        output_dir,
        separation_summary,
        method_summary,
        baseline_prevalence,
    )
    print(f"Saved analysis to {output_dir}")


def plot_results(
    output_dir: Path,
    separation: pd.DataFrame,
    separation_summary: pd.DataFrame,
    classifier_frame: pd.DataFrame,
    method_summary: pd.DataFrame,
    paired_medians: dict[str, dict[str, tuple[float, float]]],
) -> None:
    plt.style.use("seaborn-v0_8-whitegrid")
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.subplots_adjust(
        left=0.075,
        right=0.98,
        top=0.88,
        bottom=0.08,
        hspace=0.34,
        wspace=0.22,
    )

    for ax, feature_name in zip(
        axes[0],
        ("residual_rms", "freeze_log_power"),
    ):
        medians = paired_medians[feature_name]
        fog_values = np.asarray(
            [medians[subject][1] for subject in SUBJECTS],
            dtype=np.float64,
        )
        order = np.argsort(fog_values)
        value_span = max(float(np.ptp(fog_values)), 0.5)
        minimum_gap = 0.06 * value_span
        adjusted = fog_values.copy()
        for rank in range(1, len(order)):
            previous = order[rank - 1]
            current = order[rank]
            adjusted[current] = max(
                adjusted[current],
                adjusted[previous] + minimum_gap,
            )
        overflow = adjusted.max() - (fog_values.max() + 0.08 * value_span)
        if overflow > 0:
            adjusted -= overflow
        for index, subject in enumerate(SUBJECTS):
            nonfog, fog = medians[subject]
            ax.plot(
                [0, 1],
                [nonfog, fog],
                color="#90A4AE",
                linewidth=1.2,
                alpha=0.8,
            )
            ax.scatter(0, nonfog, color="#2E7D32", s=32, zorder=3)
            ax.scatter(1, fog, color="#C62828", s=32, zorder=3)
            ax.annotate(
                subject,
                xy=(1, fog),
                xytext=(1.035, adjusted[index]),
                textcoords="data",
                fontsize=8,
                va="center",
                arrowprops={
                    "arrowstyle": "-",
                    "color": "#78909C",
                    "linewidth": 0.7,
                },
            )
        ax.set_xticks([0, 1], ["non-FOG", "FOG"])
        ax.set_xlim(-0.05, 1.12)
        ax.set_ylabel(SUMMARY_FEATURE_LABELS[feature_name])
        ax.set_title(
            f"Per-subject class medians: {SUMMARY_FEATURE_LABELS[feature_name]}",
            fontweight="bold",
        )

    auc_ax = axes[1, 0]
    ordered = separation_summary.sort_values(
        "subject_macro_roc_auc",
        ascending=True,
    )
    auc_ax.barh(
        ordered["feature_label"],
        ordered["subject_macro_roc_auc"],
        color="#5C6BC0",
        alpha=0.9,
    )
    auc_ax.axvline(0.5, color="#616161", linestyle="--", linewidth=1.2)
    auc_ax.set_xlim(0.35, 1.0)
    auc_ax.set_xlabel("Subject-macro ROC-AUC (high feature = FOG)")
    auc_ax.set_title("Univariate residual-feature separation", fontweight="bold")

    metric_ax = axes[1, 1]
    plot_metrics = ("pr_auc", "roc_auc", "balanced_accuracy")
    methods = (
        "residual_rms_threshold",
        "time_frequency_logistic",
        "residual_h4s_tcn_m",
    )
    method_labels = ("RMS threshold", "TF logistic", "4 s residual TCN")
    colors = ("#78909C", "#7E57C2", "#EF6C00")
    width = 0.24
    positions = np.arange(len(plot_metrics))
    for method_index, (method, label, color) in enumerate(
        zip(methods, method_labels, colors)
    ):
        selected = method_summary.loc[
            (method_summary["method"] == method)
            & (method_summary["metric"].isin(plot_metrics))
        ].set_index("metric")
        means = np.asarray(
            [selected.loc[metric, "subject_macro_mean"] for metric in plot_metrics]
        )
        low = np.asarray(
            [selected.loc[metric, "ci_low"] for metric in plot_metrics]
        )
        high = np.asarray(
            [selected.loc[metric, "ci_high"] for metric in plot_metrics]
        )
        x = positions + (method_index - 1) * width
        metric_ax.bar(x, means, width=width, label=label, color=color)
        metric_ax.errorbar(
            x,
            means,
            yerr=np.vstack([means - low, high - means]),
            fmt="none",
            ecolor="#263238",
            capsize=3,
            linewidth=1,
        )
    metric_ax.set_xticks(positions, ["PR-AUC", "ROC-AUC", "Balanced Acc."])
    metric_ax.set_ylim(0, 1)
    metric_ax.set_title("Held-out-subject classification", fontweight="bold")
    metric_ax.legend(fontsize=9)

    fig.suptitle(
        "Daphnet GRU-H200: can normal-prediction residuals separate FOG?\n"
        "Eight held-out subjects; 2-second, 9-channel standardized residual blocks",
        fontsize=16,
        fontweight="bold",
    )
    fig.savefig(
        output_dir / "residual_feature_analysis.png",
        dpi=200,
        bbox_inches="tight",
        facecolor="white",
    )
    plt.close(fig)


def lookup_summary(
    frame: pd.DataFrame,
    method: str,
    metric: str,
) -> pd.Series:
    selected = frame.loc[
        (frame["method"] == method) & (frame["metric"] == metric)
    ]
    if len(selected) != 1:
        raise ValueError(f"Missing summary for {method}/{metric}")
    return selected.iloc[0]


def write_report(
    output_dir: Path,
    separation_summary: pd.DataFrame,
    method_summary: pd.DataFrame,
    baseline_prevalence: float,
) -> None:
    rms_sep = separation_summary.loc[
        separation_summary["feature"] == "residual_rms"
    ].iloc[0]
    freeze_sep = separation_summary.loc[
        separation_summary["feature"] == "freeze_log_power"
    ].iloc[0]
    rms_pr = lookup_summary(
        method_summary,
        "residual_rms_threshold",
        "pr_auc",
    )
    rms_roc = lookup_summary(
        method_summary,
        "residual_rms_threshold",
        "roc_auc",
    )
    rms_ba = lookup_summary(
        method_summary,
        "residual_rms_threshold",
        "balanced_accuracy",
    )
    logistic_pr = lookup_summary(
        method_summary,
        "time_frequency_logistic",
        "pr_auc",
    )
    logistic_roc = lookup_summary(
        method_summary,
        "time_frequency_logistic",
        "roc_auc",
    )
    logistic_ba = lookup_summary(
        method_summary,
        "time_frequency_logistic",
        "balanced_accuracy",
    )
    tcn_pr = lookup_summary(method_summary, "residual_h4s_tcn_m", "pr_auc")
    tcn_roc = lookup_summary(method_summary, "residual_h4s_tcn_m", "roc_auc")
    tcn_ba = lookup_summary(
        method_summary,
        "residual_h4s_tcn_m",
        "balanced_accuracy",
    )

    report = f"""# GRU-H200 residual feature separation report

## Question

Do residuals between predicted non-FOG and actual FOG carry more diagnostic
information than residuals between predicted non-FOG and actual non-FOG?

Residual definitions:

```text
NN residual = actual non-FOG - predicted normal mean
NF residual = actual FOG - predicted normal mean
```

The source is the audited eight-fold Daphnet GRU-H200 suite.  Every descriptive
test result below uses residuals from a held-out subject.

## Descriptive result

- Mean test FOG prevalence: {baseline_prevalence:.4f}.
- Residual RMS subject-macro ROC-AUC: {rms_sep['subject_macro_roc_auc']:.4f}
  [{rms_sep['roc_auc_ci_low']:.4f}, {rms_sep['roc_auc_ci_high']:.4f}];
  FOG median was higher in {int(rms_sep['subjects_fog_median_higher'])}/8 subjects.
- 3–8 Hz residual log-power subject-macro ROC-AUC:
  {freeze_sep['subject_macro_roc_auc']:.4f}
  [{freeze_sep['roc_auc_ci_low']:.4f}, {freeze_sep['roc_auc_ci_high']:.4f}];
  FOG median was higher in
  {int(freeze_sep['subjects_fog_median_higher'])}/8 subjects.

Therefore the proposed direction can be tested directly, but “FOG residual is
always larger” is not assumed; subject-level direction and overlap are retained.

## Classification result

| Method | PR-AUC | ROC-AUC | Balanced Accuracy |
|---|---:|---:|---:|
| RMS + validation threshold | {rms_pr['subject_macro_mean']:.4f} | {rms_roc['subject_macro_mean']:.4f} | {rms_ba['subject_macro_mean']:.4f} |
| Time-frequency features + logistic | {logistic_pr['subject_macro_mean']:.4f} | {logistic_roc['subject_macro_mean']:.4f} | {logistic_ba['subject_macro_mean']:.4f} |
| Existing 4 s residual TCN-M | {tcn_pr['subject_macro_mean']:.4f} | {tcn_roc['subject_macro_mean']:.4f} | {tcn_ba['subject_macro_mean']:.4f} |

The TCN reference consumes two chronological H200 blocks (4 s), whereas the
RMS and logistic analyses consume one H200 block (2 s).  They answer related
but not parameter-matched questions.

## Interpretation boundary

1. AUC above 0.5 shows residual information, not perfect FOG specificity.
2. Residual magnitude can also respond to phase error, turns, voluntary stops,
   sensor shift, and predictor domain shift.
3. Highly overlapping windows are not independent; subject-macro results and
   subject-level bootstrap intervals are the primary summaries.
4. The time-frequency logistic model is exploratory because outer-training
   residuals were generated by an NBM fitted on those same training subjects.
   A confirmatory classifier requires subject-level cross-fitted training
   residuals.
5. Effective deployment also requires event sensitivity, false alarms/hour,
   and detection delay; window PR-AUC alone is insufficient.

![Residual feature analysis](residual_feature_analysis.png)
"""
    (output_dir / "REPORT.md").write_text(report, encoding="utf-8")


if __name__ == "__main__":
    main()
